name: "Issue DueDate Reminder"
description: "Setup Issue DueDate Reminders to not miss anything."
author: "Petros Andreou"
branding:
  icon: 'clock'
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  gh_token:
    description: "The Personal Token"
    required: true
  project_number:
    description: "The Project Number"
    required: true
  notify_for:
    description: "The type of the notification are about to sent (expiring_issues,missing_duedate) "
    required: true
    default: "expiring_issues"
  duedate_field_name:
    description: "The field name"
    required: true
    default: "Due Date"
  notification_type:
    description: "The type of notification (comment,aws_email)"
    required: true
    default: 'comment'
  repository_owner_type:
    description: "The type of the repository owner (organization,user)"
    required: true
    default: 'user'
  enterprise_github:
    description: "Determines if the GitHub is the enterprise ot not (True,False)"
    required: false
    default: 'False'
  dry_run:
    description: "DryRun Mode (True,False)"
    required: false
    default: 'False'
  smtp_server:
    description: "The mail server address"
    required: false
  smtp_port:
    description: "The mail server port"
    required: false
  smtp_username:
    description: "The mail server username"
    required: false
  smtp_password:
    description: "The mail server password"
    required: false
  smtp_from_email:
    description: "The mail from email address"
    required: false
  mail_aggiuntive:
    description: "alcune mail aggiuntive a cui spedire l'alert"
    required: false
  giorni_preavviso:
    description: "giorni prima della scadenza (due date) quando mandare il preavviso"
    required: true
